version: 2.1

# Default settings for executors

orbs:
  win: circleci/windows@5.0.0

defaults: &defaults
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx3200m -Dclojure.main.report=stderr
  resource_class: large # default is medium. large (may) give us more consistent CI results

# Runners for OpenJDK

executors:
  jdk8:
    docker:
      - image: clojure:temurin-8-tools-deps-noble
    <<: *defaults
  jdk11:
    docker:
      - image: clojure:temurin-11-tools-deps-noble
    <<: *defaults
  jdk17:
    docker:
      - image: clojure:temurin-17-tools-deps-noble
    <<: *defaults
  jdk21:
    docker:
      - image: clojure:temurin-21-tools-deps-noble
    <<: *defaults
  jdk25:
    docker:
      - image: clojure:temurin-25-tools-deps-noble
    <<: *defaults

# Runs a given set of steps, with some standard pre- and post-
# steps, including restoring of cache, saving of cache.
#
# Adapted from https://github.com/lambdaisland/meta/blob/master/circleci/clojure_orb.yml

commands:
  with_cache:
    description: |
      Run a set of steps with Maven dependencies and Clojure classpath cache
      files cached.
      This command restores ~/.m2 and .cpcache if they were previously cached,
      then runs the provided steps, and finally saves the cache.
      The cache-key is generated based on the contents of `deps.edn` present in
      the `working_directory`.
    parameters:
      steps:
        type: steps
      files:
        description: Files to consider when creating the cache key
        type: string
        default: "deps.edn build/main.clj"
      cache_version:
        type: string
        description: "Key used to identify unique cache"
        default: "1"
    steps:
      - run:
          name: Generate Cache Checksum
          command: |
            for file in << parameters.files >>
            do
              find . -name $file -exec cat {} +
            done | sha256sum | awk '{print $1}' > /tmp/clojure_cache_seed
      - restore_cache:
          key: cache-<< parameters.cache_version >>-{{ checksum "/tmp/clojure_cache_seed" }}
      - steps: << parameters.steps >>
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
            - .cpcache
          key: cache-<< parameters.cache_version >>-{{ checksum "/tmp/clojure_cache_seed" }}

  setup-windows:
    steps:
      - checkout
      - run:
          name: Install scoop latest
          command: |
            Invoke-WebRequest -Uri "https://github.com/casselc/clj-msi/releases/download/v1.12.5.1645/clojure-1.12.5.1645.msi" -OutFile install.msi
            Start-Process msiexec.exe -Wait -ArgumentList "/i install.msi /qn"

jobs:

  lint:
    description: |
      Running utility commands/checks (linter etc.)
    parameters:
      clojure_version:
        type: string
        default: "1.12"
    executor: jdk25
    environment:
      CLOJURE_VERSION: << parameters.clojure_version >>
    steps:
      - checkout
      - with_cache:
          cache_version: "util_v3_<< parameters.clojure_version >>"
          steps:
            - run:
                name: Running Eastwood
                command: |
                  make eastwood
            - run:
                name: Running cljfmt
                command: |
                  make cljfmt
            - run:
                name: Running clj-kondo
                command: |
                  make kondo
            - run:
                name: Verifying Cljdoc
                command: |
                  make verify-cljdoc

  deploy:
    executor: jdk8
    steps:
      - checkout
      - run:
          name: Deploy
          command: make deploy

  test:
    description: |
      Run tests against given version of JDK and Clojure
    parameters:
      jdk_version:
        type: string
      clojure_version:
        type: string
      extra_aliases:
        type: string
        default: ""
    executor: << parameters.jdk_version >>
    environment:
      CLOJURE_VERSION: << parameters.clojure_version >>
      EXTRA_ALIASES: << parameters.extra_aliases >>
    steps:
      - checkout
      - with_cache:
          cache_version: "test_v2_<< parameters.clojure_version >>"
          steps:
            - run:
                name: Running tests
                command: make test
            - store_test_results:
                path: test-results

  test_windows:
    description: |
      Run tests on MS-Windows using the system's JDK version and Clojure 1.12.
    executor: win/default
    steps:
      - setup-windows
      - run:
          name: Running tests on Windows
          command: |
            java -version; if(-not $?){exit 9}
            clojure -T:build javac :with-tests true; if(-not $?){exit 9}
            clojure -T:build test; if(-not $?){exit 9}

run_always: &run_always
  filters:
    branches:
      only: /.*/
    tags:
      ignore: /.*SNAPSHOT$/

workflows:
  ci-test-matrix:
    jobs:
      - test:
          matrix:
            alias: "test-jdk8"
            parameters:
              clojure_version: ["1.9", "1.10", "1.11", "1.12"]
              jdk_version: [jdk8]
              # JDK8 and 11 need junitsocket library to support sockets as
              # connection target.
              extra_aliases: [":+junixsocket"]
          <<: *run_always
      - test:
          matrix:
            alias: "test-jdk11"
            parameters:
              # JDK11 is the last tested version that needs junitsocket library
              # to support sockets as connection target.
              clojure_version: ["1.12"]
              jdk_version: [jdk11]
              extra_aliases: [":+junixsocket"]
          <<: *run_always
      - test:
          matrix:
            alias: "test-older-jdk"
            parameters:
              clojure_version: ["1.12"]
              jdk_version: [jdk17, jdk21]
          <<: *run_always
      - test:
          matrix:
            alias: "test"
            parameters:
              clojure_version: ["1.10", "1.11", "1.12"]
              jdk_version: [jdk25]
          <<: *run_always
      - test_windows:
          <<: *run_always
      - lint:
          <<: *run_always
      - deploy:
          requires:
            - test-jdk8
            - test
            - lint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
      - deploy:
          name: Deploy snapshot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.+-SNAPSHOT$/
