= Release Policy

We're following link:http://semver.org/[SemVer].footnote:[As much as one can be
following it when the major version is 0.] At this point bumps of the
minor (second) version number are considered feature releases and always
include new features or significant changes to existing features. API
compatibility will almost never be broken.footnote:[Unless explicitly stated
via deprecation warnings for a few releases beforehand.]

The development cycle for the next feature
release starts immediately after the previous one has been
shipped. Bugfix/point releases (if any) address only serious bugs and
never contain new features. Here are a few examples:

* 0.5.0 - Feature release
* 0.5.1 - Bug-fix release
* 0.5.2 - Bug-fix release
* 0.6.0 - Feature release

NOTE: Historically this wasn't always the case. Versions 0.2, 0.3 and
0.4 introduced major backward-incompatible changes. Back then point
releases (e.g. 0.4.2) could mean either bug-fixes or new
backwards-compatible functionality.  That changed with nREPL 0.5 for the
sake of making it obvious which releases add new functionality and
which simply patch bugs. That brings up one step closer to the SemVer
ideal.
