= Support

nREPL currently has several official & unofficial support channels.

For questions, suggestions and support refer to one of them.  Please, don't
use the support channels to report issues, as this makes them harder to track.

== Freenode

We've got an unofficial Freenode channel - `#nrepl`. It's not actively
monitored by the nREPL maintainers themselves, but still you can get support
from other nREPL users there.

== Slack

We've got an official link:https://clojurians.slack.com/[Clojurians Slack] -
`#nrepl`. This is usually be best way to get a handle on some of the maintainers
and interact with other nREPL users.

There's also another channel named `#cider`, where often people are discussing
nREPL-related topics, as nREPL is the foundation of CIDER.

== Stackoverflow

We're also encouraging users to ask nREPL-related questions on StackOverflow.

When doing so you should use the
link:http://stackoverflow.com/questions/tagged/nrepl[nrepl] tag (ideally combined
with the tags `clojure` or `clojurescript`).
