= nREPL Clients

Most of the time, you will connect to an nREPL server using an existing
library/client/tool. Below is a listing of many such clients.

NOTE: Some of these clients will only work with Clojure nREPL servers, while
others are built with language-agnosticism and can connect to nREPL
servers written in any language.

== Command-line Clients

* https://github.com/trptcolin/reply/[REPL-y] (command-line client for nREPL)
* https://github.com/bhauman/rebel-readline/tree/master/rebel-readline-nrepl[rebel-readline] (advanced command-line client for nREPL)
* https://github.com/eraserhd/rep[rep] (A single-shot nREPL client designed for shell invocation.)
* https://git.sr.ht/~technomancy/shevek/[shevek] (A command-line nREPL client written in https://fennel-lang.org/[Fennel], works with non-Clojure servers)
* https://github.com/kanej/parle[Parle] (A command-line nREPL client using node.js written in ClojureScript)
* https://github.com/licht1stein/brepl[brepl] (A fast babashka based command-line nREPL client)
* https://github.com/waddie/nautilos[Nautilos] (An LLM-oriented command-line nREPL client written in https://janet-lang.org[Janet], works with non-Clojure servers)

NOTE: Leiningen uses REPL-y internally as its command-line nREPL client.

== Editors/IDEs

* https://github.com/clojure-emacs/cider[CIDER] (Clojure Interactive
  Development Environment that Rocks for Emacs)
* https://cursiveclojure.com[Cursive] (Clojure IDE/plugin for IntelliJ Idea)
* https://github.com/sanel/monroe[monroe] (nREPL client for Emacs, works with non-Clojure servers)
* https://github.com/Sasanidas/Rail[Rail] (generic nREPL client for Emacs that should work with any nREPL server)
* https://github.com/tpope/vim-fireplace[fireplace.vim] (Clojure + nREPL
  support for vim)
* https://github.com/Olical/conjure[Conjure] (Clojure(Script) plugin for Neovim)
* https://github.com/liquidz/vim-iced[vim-iced] (Clojure Interactive Development Environment for Vim8/Neovim)
* https://github.com/BetterThanTomorrow/calva[Calva] (Clojure & ClojureScript support for VS Code)
* https://github.com/tonsky/Clojure-Sublimed[Clojure Sublimed] (Clojure support for Sublime Text)
* https://github.com/waddie/nrepl.hx[nREPL.hx] (nREPL client for Helix, works with non-Clojure servers)

If your preferred Clojure development environment supports nREPL, you're in luck.
Just use it or connect to an existing nREPL endpoint and start hacking.

TIP: Most Clojure editors/IDEs can start an nREPL server themselves and connect
to it automatically (e.g. CIDER would do this when you're using the
`cider-jack-in` family of commands), so you'll rarely need to start a server
externally for local development purposes.

== Libraries

* https://github.com/rksm/node-nrepl-client[node-nrepl-client] (An nREPL client for programmatic use from node.js written in Javascript)
* https://github.com/clojure-vim/nrepl-python-client[nrepl-python-client] (nREPL client library for Python)
* https://github.com/vspinu/R-nREPL[R-nREPL] (nREPL client for R)

== Other Clients

* https://github.com/clojupyter/clojupyter[clojupyter] (Jupyter notebooks for Clojure)

== Using the built-in client

nREPL ships with a very simple command-line client that you can use for some basic
interactions with the server. The following command will start an nREPL server
and connect with it using the built-in client.

[source,shell]
----
$ clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "1.7.0"}}}' -M -m nrepl.cmdline --interactive
nREPL server started on port 59403 on host 127.0.0.1 - nrepl://127.0.0.1:59403
nREPL 1.7.0
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
user=> (+ 1 2)
3
----

If you want to connect to a server that's already running you can do it like this:

[source,shell]
----
$ clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "1.7.0"}}}' -M -m nrepl.cmdline --connect --host host --port port
nREPL 1.7.0
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
user=> (+ 1 2)
3
----

If you want to connect to a unix domain socket, you can do it like this:

[source,shell]
----
$ clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "1.7.0"}}}' -M -m nrepl.cmdline --connect --socket /some/where/safe/nrepl
nREPL 1.7.0
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
user=> (+ 1 2)
3
----

You can also connect using a URL, by passing it as the `--host` value. The
transport is chosen from the URL's scheme, so `--transport` and `--port` are
ignored in this case:

[source,shell]
----
$ clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "1.7.0"}}}' -M -m nrepl.cmdline --connect --host nrepl://127.0.0.1:59403
nREPL 1.7.0
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 10.0.1+10
user=> (+ 1 2)
3
----

The built-in schemes are `nrepl` (the default Bencode transport) and
`nrepl+edn` (the EDN transport).

A TLS-enabled server advertises a TLS URL in its startup message - `nrepls://`
(Bencode) or `nrepl+edns://` (EDN) - and you can connect using that URL. You
still have to supply the client keys, so combine it with `--tls-keys-file` (or
`--tls-keys-str`; see the xref:usage/tls.adoc[TLS documentation]):

[source,shell]
----
$ clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "1.7.0"}}}' -M -m nrepl.cmdline --connect --host nrepls://127.0.0.1:4001 --tls-keys-file client.keys
----

Connecting over HTTP or HTTPS is also
supported via the https://github.com/nrepl/drawbridge[Drawbridge] library -
add `nrepl/drawbridge` to your dependencies and connect with an `http://` or
`https://` URL:

[source,shell]
----
$ clj -Sdeps '{:deps {nrepl/nrepl {:mvn/version "1.7.0"} nrepl/drawbridge {:mvn/version "0.3.1"}}}' -M -m nrepl.cmdline --connect --host https://your-app.example.com/repl
----

If Drawbridge isn't on the classpath, the client will tell you to add it.

The built in client does not support the tty transport. Use `nc` or `telnet` instead.

Most users, however, are advised to use REPL-y or their favourite
editor instead for optimal results.

== Talking to an nREPL endpoint programmatically

If you want to connect to an nREPL server using the default transport, something
like this will work:

[source,clojure]
----
=> (require '[nrepl.core :as nrepl])
nil
=> (with-open [conn (nrepl/connect :port 59258)]
     (-> (nrepl/client conn 1000)    ; message receive timeout required
         (nrepl/message {:op "eval" :code "(+ 2 3)"})
         nrepl/response-values))
----

If your nREPL server is running on a different machine or listening on a specific
address different than the default one, you can use the `:host` keyword in the
`connect` function to specify which address to connect to. E.g., to
connect to a nREPL server listening on address 172.18.0.5 and port 4001:

[source,clojure]
----
=> (with-open [conn (nrepl/connect :host "172.18.0.5" :port 4001)]
     (-> (nrepl/client conn 1000)    ; message receive timeout required
         (nrepl/message {:op "eval" :code "(+ 2 3)"})
         nrepl/response-values))
----

`response-values` will return only the values of evaluated expressions, read
from their (by default) `pr`-encoded representations via `read`.  You can see
the full content of message responses easily:

[source,clojure]
----
=> (with-open [conn (nrepl/connect :port 59258)]
     (-> (nrepl/client conn 1000)
         (nrepl/message {:op "eval" :code "(time (reduce + (range 1e6)))"})
         doall      ;; `message` and `client-session` all return lazy seqs
         pprint))
nil
({:out "\"Elapsed time: 68.032 msecs\"\n",
  :session "2ba81681-5093-4262-81c5-edddad573201",
  :id "3124d886-7a5d-4c1e-9fc3-2946b1b3cfaa"}
 {:ns "user",
  :value "499999500000",
  :session "2ba81681-5093-4262-81c5-edddad573201",
  :id "3124d886-7a5d-4c1e-9fc3-2946b1b3cfaa"}
 {:status ["done"],
  :session "2ba81681-5093-4262-81c5-edddad573201",
  :id "3124d886-7a5d-4c1e-9fc3-2946b1b3cfaa"})
----

Each message must contain at least an `:op` (or `"op"`) slot, which specifies
the "type" of the operation to be performed.  The operations supported by an
nREPL endpoint are determined by the handlers and middleware stack used when
starting that endpoint; the default middleware stack (described below) supports
a particular set of operations, xref:ops.adoc[detailed here].
