= FAQ

== What's the difference between contrib's nREPL and this one?

See link:https://docs.nrepl.xyz/en/latest/about/history/[our history].
Very simply put - this project is the continuation of the contrib project.

== Does nREPL support ClojureScript?

Yes, it does, although you'll need additional middleware to enable the
ClojureScript support
(e.g. link:https://github.com/nrepl/piggieback[piggieback] or
link:https://github.com/thheller/shadow-cljs[shadow-cljs]).

== Does nREPL support ClojureCLR?

nREPL currently doesn't support ClojureCLR. The reason for this is
that it leverages Java APIs internally. There's an link:https://github.com/clojure/clr.tools.nrepl[nREPL port for ClojureCLR], but it's not
actively maintained and it doesn't behave like the Clojure nREPL.

== When is nREPL 1.0 going to be released?

There's no exact roadmap for the 1.0 release. Roughly speaking the idea is to
release 1.0 once everything essential has been migrated from the legacy contrib nREPL
to the new nREPL (e.g. lein, boot, key middleware) and we've cleaned up the most
important tickets from our backlog.

== Are there any interesting nREPL extensions worth checking out?

Sure! See <<third_party_middleware.adoc#,third party middleware>> for details.

== Where can I get help regarding nREPL?

See the <<about/support.adoc#,Support>> section of the manual.

== What should I do if I run into some issues with nREPL?

Don't panic! Next step - visit the <<troubleshooting.adoc#,Troubleshooting>> section of
the manual.

== How can I help the project?

There are many ways in which you can help nREPL:

* Donate funds
* Work on improving the documentation
* Solve open issues
* File bug reports and suggestions for improvements
* Promote nREPL via blog posts or at meetups and conferences
* Invite members of the nREPL team to speak about nREPL at meetups and conferences
