= FAQ

== What's the difference between contrib's nREPL and this one?

See xref:about/history.adoc[our history]. Very simply put - this project is the
continuation of the contrib project. There were several major changes that
happened during the migration:

* The artifact id changed from `org.clojure/clojure.tools.nrepl` to `nrepl/nrepl`.
* The namespace prefix changed from `clojure.tools.nrepl` to `nrepl`.
* The namespace `clojure.tools.nrepl` was renamed to `nrepl.core`.
* Minimal requirements changed from Java 6 and Clojure 1.2 to Java 8 and Clojure 1.7.
* All the code which existed for compatibility with nREPL 0.0.x was removed.

== What's the plural form of "middleware"?

The plural form of "middleware" is "middleware", not "middlewares".footnote:[See https://english.stackexchange.com/questions/257120/middleware-vs-middlewares for a
discussion on the subject] While there's https://www.wordhippo.com/what-is/the-plural-of/middleware.html[some debate] on whether its okay to write something like "a collection of middlewares", we've opted
to stick to using "middleware" everywhere in both the codebase and the documentation.

== Does nREPL support ClojureScript?

Yes, it does, although you'll need additional middleware to enable the
ClojureScript support
(e.g. https://github.com/nrepl/piggieback[piggieback] or
https://github.com/thheller/shadow-cljs[shadow-cljs]).

== Does nREPL support ClojureCLR?

There is a separate implementation of nREPL for ClojureCLR: https://github.com/clojure/clr.tools.nrepl[https://github.com/clojure/clr.tools.nrepl].

== When is nREPL 1.0 going to be released?

nREPL 1.0 was released on August 24, 2022. This completes the promise we made
way back in 2018 to address most languishing problems and get nREPL
in a great shape.

Future releases will focus on polishing the nREPL protocol and potentially
adding some https://github.com/nrepl/nrepl/discussions/275[new features].

== Are there any interesting nREPL extensions worth checking out?

Sure! See xref:extensions.adoc[Extensions] for details.

== Where can I get help regarding nREPL?

See the xref:about/support.adoc[Support] section of the manual.

== What should I do if I run into some issues with nREPL?

Don't panic! Next step - visit the xref:troubleshooting.adoc[Troubleshooting] section of
the manual.

== How can I help the project?

There are many ways in which you can help nREPL:

* Donate funds
* Work on improving the documentation
* Solve open issues
* File bug reports and suggestions for improvements
* Promote nREPL via blog posts or at meetups and conferences
* Invite members of the nREPL team to speak about nREPL at meetups and conferences
