= Hacking on nREPL

== Building nREPL

Releases are available from Clojars, and SNAPSHOT builds from master's
HEAD are automatically deployed there as well, so manually building
nREPL shouldn't ever be necessary (unless you're hacking on it).  But,
if you insist:

. Clone the repo
. Make sure you have lein installed
. Run the lein build:

[source,shell]
----
$ lein install
----

Afterwards you can simply do something like:

[source,shell]
----
$ clj -Sdeps '{:deps {nrepl {:mvn/version "0.5.2-SNAPSHOT"}}}' -m nrepl.cmdline --interactive
----

== Running the tests

The easiest way to run the tests is with the following command:

[source,shell]
----
$ lein test-all
----

This will automatically run the tests for every supported Clojure
profile (e.g. 1.7, 1.8, 1.9). You can run only the tests for a
specific version of Clojure like this:

[source,shell]
----
$ lein with-profile 1.9 test
----

== Logging nREPL messages

You can start the server with the verbose flag set to true, there's
a default logger that logs the input and output messages with `log/info`,
but a op `logger` is available so you can set the field `logger` to some
namespaced symbol representing a function.

See more at test `logger` at `nrepl.core-test`.
