= Installation

[NOTE]
====
nREPL is compatible with Clojure 1.7.0+ and Java 8+.
====

nREPL is a library (as opposed to it being an application), so it's
not something you'd be installing in the traditional sense. There's
currently no nREPL binary or script that you can run to spin a server.

[NOTE]
====
While there's no binary, there is a command-line interface that
mostly targets `clj`. It's documented in the subsequent sections of this
manual.
====

All popular Clojure build tools (Leiningen, Boot, Gradle, Maven) have
the ability to run an nREPL server and most of the time you'll probably
simply use nREPL through them and end up using whatever nREPL version
they happen to ship.

Still, from time to time you'll be building a tool around nREPL or you'll
want to embed an nREPL server directly in your application. In those
scenarios some kind of an installation will be in order - just adding
nREPL as a dependency to your project.

nREPL is available in Clojars. Add this to your Leiningen
`project.clj` `:dependencies`:

[source,clojure]
----
[nrepl "1.1.1"]
----

[TIP]
====
You can override the version of nREPL supplied by Leiningen and Boot by
adding nREPL as a dependency to your project.
====

Or, add this to your Gradle project's `build.gradle`:

[source, groovy]
----
dependencies {
  // to use as a library in your code
  implementation 'nrepl:nrepl:1.1.1'

  // or to override the version of nREPL used by the clojureRepl task
  nrepl 'nrepl:nrepl:1.1.1'
}
----

Or, add this to your Maven project's `pom.xml`:

[source,xml]
----
<dependency>
  <groupId>nrepl</groupId>
  <artifactId>nrepl</artifactId>
  <version>1.1.1</version>
</dependency>
----
